/*Jiayin Xie ICS3U Jun 21
    This program can help people to calculate the data about annuities.

*/
import java.awt.Color;
import java.text.DecimalFormat;


public class AnnuityCalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form AnnuityCalculatorFrame
     */
    DecimalFormat d = new DecimalFormat("###.##");
    int a; //determine if the user entered only 4 of the data
    int f=0; //frequency -- Weekly=52 Monthly=12 Quaterly=4 Semiyearly=2 Yearly=1
    
    public AnnuityCalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        frequencyCbIn = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        save = new javax.swing.JRadioButton();
        pay = new javax.swing.JRadioButton();
        interest = new javax.swing.JTextField();
        pv = new javax.swing.JTextField();
        duration = new javax.swing.JTextField();
        promptLabel = new javax.swing.JLabel();
        Calculate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        regular = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel6.setText("jLabel6");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jFormattedTextField1.setText("jFormattedTextField1");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 212, 212));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Annuity Calculator");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Interest rate per year (%)");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Future value/Loan ($)");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Duration (yrs)");

        frequencyCbIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------", "Weekly", "Monthly", "Quaterly", "Semiyearly", "Yearly" }));
        frequencyCbIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyCbInActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Frequency");

        buttonGroup1.add(save);
        save.setText("Saving money");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        buttonGroup1.add(pay);
        pay.setText("Paying Loan");

        promptLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        promptLabel.setForeground(new java.awt.Color(0, 153, 51));

        Calculate.setText("Calculate");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Regular payment ($)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(frequencyCbIn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(interest)
                                    .addComponent(pv)
                                    .addComponent(duration)
                                    .addComponent(regular)))
                            .addComponent(promptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(save)
                                .addGap(69, 69, 69)
                                .addComponent(pay)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(promptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(interest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(frequencyCbIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pay)
                    .addComponent(save))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(Calculate)
                .addGap(50, 50, 50))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frequencyCbInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequencyCbInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frequencyCbInActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed
    
    public int findEnteredNumber(){
        
        a=0;
        
        if(interest.getText().isEmpty()==false)
        {
            a++;
        }
        if(pv.getText().isEmpty()==false)
        {
            a++;
        }
        if(duration.getText().isEmpty()==false)
        {
            a++;
        }
        if(frequencyCbIn.getSelectedIndex()!=0)
        {
            a++;
            switch(frequencyCbIn.getSelectedIndex()) //determine the value of frequency
            {
                case 1:
                    f=52;
                    break;
                case 2:
                    f=12;
                    break;
                case 3:
                    f=4;
                    break;
                case 4:
                    f=2;
                    break;
                case 5:
                    f=1;
                    break;
            }
        }
        if(regular.getText().isEmpty()==false)
        {
            a++;
        }
        return a;
    }
    
        private void calculateInterestSaving(){
            
            promptLabel.setText("Sorry, can't calculate interest.");
            promptLabel.setForeground(Color.red);
                
        }
        private void calculatePvSaving(){
            
            double FV;
                    
            promptLabel.setText("Future value calculated!");
            promptLabel.setForeground(Color.green);
                    
            double i=Double.parseDouble(interest.getText());
            i=i/100/f;
            double n=Double.parseDouble(duration.getText())*f;
            double r=Double.parseDouble(regular.getText());

                    
            FV=r*((Math.pow(1+i,n)-1)/i);
                    
            pv.setText(d.format(FV));
                    
                
        }
        private void calculateLoanPaying(){
            
            double PV=0;
                    
            promptLabel.setText("Loan calculated!");
            promptLabel.setForeground(Color.green);
                    
            double i=Double.parseDouble(interest.getText())/100/f;
            int n=Integer.parseInt(duration.getText())*f;
            double r=Double.parseDouble(regular.getText());
                    
                    
            PV=r*(1-Math.pow(1+i, -n))/i;
                    
            pv.setText(d.format(PV));
                    
                
        }
        private void calculateDurationSaving(){
            double n;
                    
            promptLabel.setText("Duration calculated!");
            promptLabel.setForeground(Color.green);
                    
            double i=Double.parseDouble(interest.getText())/100/f;
            double p=Double.parseDouble(pv.getText());
            double r=Double.parseDouble(regular.getText());
                    
                    
            n=Math.log(p*i/r+1)/(Math.log(1+i)*f);
                    
            duration.setText(d.format(n));
                    
                
        }
        private void calculateDurationPaying(){
            double n=0;
                    
            promptLabel.setText("Duration calculated!");
            promptLabel.setForeground(Color.green);
                    
            double i=Double.parseDouble(interest.getText())/100/f;
            double p=Double.parseDouble(pv.getText());
            double r=Double.parseDouble(regular.getText());
                    
                    
            n=-(Math.log(1-p*i/r)/(Math.log(1+i)*f)); 
                    
            duration.setText(d.format(n));
                
        }
        private void calculateRegularSaving(){
            
            double r=0;
                    
            promptLabel.setText("Regular payment calculated");
            promptLabel.setForeground(Color.green);
                    
            double i=Double.parseDouble(interest.getText())/100/f;
            int n=Integer.parseInt(duration.getText())*f;
            double p=Double.parseDouble(pv.getText());

                    
            r=p*i/(Math.pow(1+i,n)-1);
                    
            regular.setText(d.format(r));
                
        }
        private void calculateRegularPaying(){
            double r=0;
                    
            promptLabel.setText("Regular payment calculated!");
            promptLabel.setForeground(Color.green);
                    
            double i=Double.parseDouble(interest.getText())/100/f;
            int n=Integer.parseInt(duration.getText())*f;
            double p=Double.parseDouble(pv.getText());

                    
            r=p*i/(1-Math.pow(1+i, -n));
                    
            regular.setText(d.format(r));
                
        }
        private void calculateFrequencySaving(){
            promptLabel.setText("Sorry, can't calculate frequency.");
            promptLabel.setForeground(Color.red);
        }
//----------------------------------------------------------------------------------------------------------------------
    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        int num=findEnteredNumber();
//----------------------------------------------------------------------------------------------------------------------
        
        if(num==4) //if only 4 boxes are entered
        {
            if(save.isSelected()==true) 
            {
                if(interest.getText().isEmpty()==true)
                {
                    calculateInterestSaving();
                }
                if(pv.getText().isEmpty()==true)
                {
                    calculatePvSaving();
                }
                if(duration.getText().isEmpty()==true)
                {
                    calculateDurationSaving();
                }
                if(regular.getText().isEmpty()==true)
                {
                    calculateRegularSaving();
                }
                if(frequencyCbIn.getSelectedIndex()==0)
                {
                    calculateFrequencySaving();
                }
                
            }
            else if(pay.isSelected()==true)//----------------------------------------------------------------------------
            {
                
                if(interest.getText().isEmpty()==true)
                { 
                    calculateInterestSaving();
                }
                if(pv.getText().isEmpty()==true)
                {
                    calculateLoanPaying();
                }
                if(duration.getText().isEmpty()==true)
                {
                    calculateDurationPaying();
                }
                if(frequencyCbIn.getSelectedIndex()==0)
                {
                    calculateFrequencySaving();
                }
                if(regular.getText().isEmpty()==true)
                {
                    calculateRegularPaying();
                }
                
            }
            else
            {
                promptLabel.setText("Please chose saving or paying!");
                promptLabel.setForeground(Color.red);
            }
        }
        else
        {
            promptLabel.setText("Please enter only 4 of them");
            promptLabel.setForeground(Color.red);
        }
        
        //----------------------------------------------------------------------
        
        
        
    }//GEN-LAST:event_CalculateActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new helpFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnnuityCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnnuityCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnnuityCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnnuityCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnnuityCalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField duration;
    private javax.swing.JComboBox<String> frequencyCbIn;
    private javax.swing.JTextField interest;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton pay;
    private javax.swing.JLabel promptLabel;
    private javax.swing.JTextField pv;
    private javax.swing.JTextField regular;
    private javax.swing.JRadioButton save;
    // End of variables declaration//GEN-END:variables
}
